inventario_homepage:
    path:     /Inventario/Producto
    defaults: { _controller: InventarioBundle:Default:index }
Almacen_homepage:
    path:     /Inventario/Almacen
    defaults: { _controller: InventarioBundle:Default:almacen }
Proveedor_homepage:
    path:     /Inventario/Proveedor
    defaults: { _controller: InventarioBundle:Default:proveedor }
ver_homepage:
    path:     /Inventario/ver
    defaults: { _controller: InventarioBundle:Default:ver }