fabricacion:
    resource: "@FabricacionBundle/Resources/config/routing.yml"
    prefix:   /

contabilidad:
    resource: "@ContabilidadBundle/Resources/config/routing.yml"
    prefix:   /

compras:
    resource: "@ComprasBundle/Resources/config/routing.yml"
    prefix:   /

parte_horas:
    resource: "@ParteHorasBundle/Resources/config/routing.yml"
    prefix:   /

tablon_anuncios:
    resource: "@TablonAnunciosBundle/Resources/config/routing.yml"
    prefix:   /

ventas:
    resource: "@VentasBundle/Resources/config/routing.yml"
    prefix:   /

proyectos:
    resource: "@ProyectosBundle/Resources/config/routing.yml"
    prefix:   /

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"
    prefix:   /

punto_venta:
    resource: "@PuntoVentaBundle/Resources/config/routing.yml"
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /

agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

personal:
    resource: "@PersonalBundle/Resources/config/routing.yml"
    prefix:   /

inventario:
    resource: "@InventarioBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
