agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

personal:
    resource: "@PersonalBundle/Resources/config/routing.yml"
    prefix:   /

inventario:
    resource: "@InventarioBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
