usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /

agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
