ParteHorasBundle\Entity\Almacen:
    type: entity
    table: Almacen
    id:
        idalmacen:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: IDAlmacen
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: Nombre
        direccion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: Direccion
    lifecycleCallbacks: {  }
