ParteHorasBundle\Entity\Bajasmedicas:
    type: entity
    table: BajasMedicas
    id:
        idBaja:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_baja
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        caracteristicas:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
