ParteHorasBundle\Entity\Cliente:
    type: entity
    table: Cliente
    id:
        idcliente:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idCliente
            generator:
                strategy: IDENTITY
    fields:
        nombreempresa:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: nombreEmpresa
        telefono:
            type: integer
            nullable: false
            options:
                unsigned: false
        email:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
    lifecycleCallbacks: {  }
