ParteHorasBundle\Entity\Departamentos:
    type: entity
    table: Departamentos
    id:
        idDepartamento:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_departamento
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        caracteristicas:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
