ParteHorasBundle\Entity\Gestionbajas:
    type: entity
    table: GestionBajas
    indexes:
        id_empleado:
            columns:
                - id_empleado
        id_baja:
            columns:
                - id_baja
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaInicio:
            type: date
            nullable: false
            column: fecha_inicio
        fechaFin:
            type: date
            nullable: false
            column: fecha_fin
        diaHabiles:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dia_habiles
    manyToOne:
        idEmpleado:
            targetEntity: Empleados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_empleado:
                    referencedColumnName: id_empleado
            orphanRemoval: false
        idBaja:
            targetEntity: Bajasmedicas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_baja:
                    referencedColumnName: id_baja
            orphanRemoval: false
    lifecycleCallbacks: {  }
