ParteHorasBundle\Entity\Modulo:
    type: entity
    table: Modulo
    id:
        idModulo:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Modulo
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: Descripcion
        activo:
            type: boolean
            nullable: false
            column: Activo
    lifecycleCallbacks: {  }
