ParteHorasBundle\Entity\Permisosvacaciones:
    type: entity
    table: PermisosVacaciones
    id:
        idpermiso:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idPermiso
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        caracteristicas:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
