ParteHorasBundle\Entity\Productos:
    type: entity
    table: Productos
    id:
        idproducto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: IDProducto
            generator:
                strategy: IDENTITY
    fields:
        nombreproducto:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: NombreProducto
        precio:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: Precio
        material:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Material
        puntoventa:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PuntoVenta
    lifecycleCallbacks: {  }
