ParteHorasBundle\Entity\Proyecto:
    type: entity
    table: Proyecto
    id:
        idProyecto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Proyecto
            generator:
                strategy: IDENTITY
    fields:
        tituloProyecto:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: Titulo_Proyecto
        descripcionProyecto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Descripcion_Proyecto
        jefeProyecto:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Jefe_Proyecto
    lifecycleCallbacks: {  }
