ParteHorasBundle\Entity\Tareas:
    type: entity
    table: tareas
    id:
        idtarea:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idTarea
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        estado:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
